#########################################
# Basic geometry visualization commands #
#########################################

# Open an OpenGL visualization
/vis/open OGL 600x600-0+0
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#/vis/verbose 1

# Draw the detector and set the view parameters
/vis/drawVolume
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 45 0
/vis/viewer/zoom 1.4
/vis/scene/add/axes 0 0 0 1 m

# Set trajectory options
/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

# To draw only gammas:
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add neutron

# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
/vis/filtering/trajectories/particleFilter-0/invert true

# To run beamOn several times and show all the events accumulated
#/vis/scene/endOfEventAction accumulate
